"use client";

import { type ChangeEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";

import { MatchEndpointCard } from "@/components/MatchEndpointCard";
import { StatePanel } from "@/components/StatePanel";
import { TeamFlag } from "@/components/TeamFlag";
import { errorMessages } from "@/lib/errors/messages";
import { exportEndpointsToJson } from "@/lib/export/exportJson";
import type { GeneratedMatchRecord, GenerationResult, MatchSourceContext } from "@/lib/types/domain";
import type { MatchEndpoint } from "@/lib/types/endpoint";

interface ApiErrorResponse {
  error?: {
    title?: string;
    detail?: string;
  };
}

function getErrorMessage(payload: ApiErrorResponse | null): string {
  if (!payload?.error) {
    return errorMessages.generationFailedDetail;
  }

  const title = payload.error.title ?? errorMessages.generationFailedTitle;
  const detail = payload.error.detail ?? errorMessages.generationFailedDetail;

  return `${title}: ${detail}`;
}

function downloadText(fileName: string, content: string): void {
  const blob = new Blob([content], {
    type: "application/json",
  });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");

  anchor.href = url;
  anchor.download = fileName;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}

function downloadAllEndpoints(fileName: string, endpoints: MatchEndpoint[]): void {
  downloadText(fileName, exportEndpointsToJson(endpoints));
}

function downloadSingleEndpoint(fileName: string, endpoint: MatchEndpoint): void {
  downloadText(fileName, JSON.stringify(endpoint, null, 2));
}

function formatDateTime(value: string): string {
  const parsed = new Date(value);

  if (Number.isNaN(parsed.getTime())) {
    return value;
  }

  return new Intl.DateTimeFormat("en-GB", {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(parsed);
}

function getStatusTone(status: string): "status-live" | "status-finished" | "status-scheduled" {
  const normalized = status.trim().toLowerCase();

  if (normalized.includes("live") || normalized.includes("progress")) {
    return "status-live";
  }

  if (normalized.includes("finished") || normalized.includes("full") || normalized.includes("ended")) {
    return "status-finished";
  }

  return "status-scheduled";
}

type MatchListGrouping = "all" | "round";
type EndpointViewMode = "json" | "simplified";

interface MatchListSection {
  key: string;
  title: string;
  records: GeneratedMatchRecord[];
}

export default function HomePage() {
  const hasAutoGeneratedRef = useRef<boolean>(false);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [isSourceContextLoading, setIsSourceContextLoading] = useState<boolean>(false);
  const [showSourceContext, setShowSourceContext] = useState<boolean>(false);
  const [error, setError] = useState<string>("");
  const [sourceContextError, setSourceContextError] = useState<string>("");
  const [matchListGrouping, setMatchListGrouping] = useState<MatchListGrouping>("all");
  const [endpointViewMode, setEndpointViewMode] = useState<EndpointViewMode>("json");
  const [result, setResult] = useState<GenerationResult | null>(null);
  const [selectedRecord, setSelectedRecord] = useState<GeneratedMatchRecord | null>(null);
  const [sourceContextByMatchCode, setSourceContextByMatchCode] = useState<
    Record<string, MatchSourceContext>
  >({});

  const endpoints = useMemo(() => {
    if (!result) {
      return [];
    }

    return result.matches.map((item: GenerationResult["matches"][number]) => item.endpoint);
  }, [result]);

  const matchListSections = useMemo<MatchListSection[]>(() => {
    if (!result) {
      return [];
    }

    if (matchListGrouping === "all") {
      return [
        {
          key: "all",
          title: "All matches",
          records: result.matches,
        },
      ];
    }

    const groupedByRound = new Map<string, GeneratedMatchRecord[]>();

    for (const record of result.matches) {
      const round = record.endpoint.competition.round.trim() || "Unknown Round";
      const existing = groupedByRound.get(round);

      if (existing) {
        existing.push(record);
        continue;
      }

      groupedByRound.set(round, [record]);
    }

    return Array.from(groupedByRound.entries()).map(([round, records]) => ({
      key: round,
      title: round,
      records,
    }));
  }, [matchListGrouping, result]);

  const handleGenerate = useCallback(async (): Promise<void> => {
    setIsLoading(true);
    setError("");

    try {
      const response = await fetch("/api/generate", {
        method: "POST",
      });

      if (!response.ok) {
        const payload = (await response.json().catch(() => null)) as ApiErrorResponse | null;
        setResult(null);
        setError(getErrorMessage(payload));
        return;
      }

      const payload = (await response.json()) as GenerationResult;

      setResult(payload);
      setSelectedRecord(null);
      setShowSourceContext(false);
      setSourceContextError("");
      setSourceContextByMatchCode({});
    } catch {
      setResult(null);
      setSelectedRecord(null);
      setShowSourceContext(false);
      setSourceContextError("");
      setSourceContextByMatchCode({});
      setError(errorMessages.generationFailedDetail);
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    setShowSourceContext(false);
    setSourceContextError("");
    setIsSourceContextLoading(false);
  }, [selectedRecord?.source.matchCode]);

  useEffect(() => {
    if (hasAutoGeneratedRef.current) {
      return;
    }

    hasAutoGeneratedRef.current = true;
    void handleGenerate();
  }, [handleGenerate]);

  const handleExport = (): void => {
    if (endpoints.length === 0) {
      return;
    }

    downloadAllEndpoints("olympic-football-endpoints.json", endpoints);
  };

  const handleOpenApi = (): void => {
    window.open("/api/generate", "_blank", "noopener,noreferrer");
  };

  const handleOpenSingleMatchApi = (matchCode: string): void => {
    const encodedMatchCode = encodeURIComponent(matchCode);
    window.open(`/api/generate?matchCode=${encodedMatchCode}`, "_blank", "noopener,noreferrer");
  };

  const handleExportSingleMatch = (record: GeneratedMatchRecord): void => {
    downloadSingleEndpoint(`olympic-football-endpoint-${record.source.matchCode}.json`, record.endpoint);
  };

  const selectedSourceContext = selectedRecord
    ? sourceContextByMatchCode[selectedRecord.source.matchCode]
    : undefined;

  const loadSourceContext = useCallback(async (matchCode: string): Promise<void> => {
    setIsSourceContextLoading(true);
    setSourceContextError("");

    try {
      const response = await fetch(
        `/api/generate?matchCode=${encodeURIComponent(matchCode)}&includeSourceContext=true`,
        {
          method: "GET",
          cache: "no-store",
        },
      );

      if (!response.ok) {
        const payload = (await response.json().catch(() => null)) as ApiErrorResponse | null;
        setSourceContextError(getErrorMessage(payload));
        return;
      }

      const payload = (await response.json()) as GenerationResult;
      const sourceContext = payload.matches[0]?.source.sourceContext;

      if (!sourceContext) {
        setSourceContextError("Full source context is not available for the selected match.");
        return;
      }

      setSourceContextByMatchCode((previous: Record<string, MatchSourceContext>) => ({
        ...previous,
        [matchCode]: sourceContext,
      }));
    } catch {
      setSourceContextError("Unable to load full source context for the selected match.");
    } finally {
      setIsSourceContextLoading(false);
    }
  }, []);

  const handleToggleSourceContext = (): void => {
    if (!selectedRecord) {
      return;
    }

    const nextValue = !showSourceContext;
    const matchCode = selectedRecord.source.matchCode;

    setShowSourceContext(nextValue);

    if (!nextValue) {
      return;
    }

    if (sourceContextByMatchCode[matchCode] || isSourceContextLoading) {
      return;
    }

    void loadSourceContext(matchCode);
  };

  const handleMatchListGroupingChange = (event: ChangeEvent<HTMLSelectElement>): void => {
    const nextGrouping = event.target.value === "round" ? "round" : "all";

    setMatchListGrouping(nextGrouping);
  };

  const matchListPanel = result ? (
    <aside className="match-list-panel" aria-label="Generated football match list">
      <header>
        <h2>Matches</h2>
        <p>{result.matches.length} fixtures available</p>
        <p className="list-meta">Generated at {formatDateTime(result.diagnostics.generatedAt)}</p>

        <div className="match-list-controls">
          <label className="match-list-controls-label" htmlFor="match-list-grouping">
            Grouping
          </label>
          <select
            id="match-list-grouping"
            className="match-list-controls-select"
            value={matchListGrouping}
            onChange={handleMatchListGroupingChange}
          >
            <option value="all">All matches</option>
            <option value="round">By round</option>
          </select>
        </div>
      </header>

      <div className="match-list-scroll">
        {matchListSections.map((section: MatchListSection) => (
          <section key={section.key} className="match-list-section">
            {matchListGrouping === "round" && <h3 className="match-list-section-heading">{section.title}</h3>}

            <div className="match-list-section-items">
              {section.records.map((record: GenerationResult["matches"][number]) => (
                <MatchEndpointCard
                  key={record.source.matchCode}
                  record={record}
                  isSelected={selectedRecord?.source.matchCode === record.source.matchCode}
                  onOpen={setSelectedRecord}
                />
              ))}
            </div>
          </section>
        ))}
      </div>
    </aside>
  ) : null;

  return (
    <main className="match-workspace">
      <header className="workspace-header">
        <div>
          <p className="workspace-eyebrow">Paris 2024 Football</p>
          <h1>footy-scores</h1>
          <p className="workspace-subtitle">
            Compact fixture list for inspection. Select any match to review generated payload details and source data.
          </p>
        </div>

        <div className="workspace-actions">
          <button className="control-button secondary" onClick={handleOpenApi} type="button">
            Open API JSON
          </button>
          <button
            className="control-button secondary"
            onClick={handleExport}
            disabled={endpoints.length === 0}
            type="button"
          >
            Export All
          </button>
          <button className="control-button" onClick={handleGenerate} disabled={isLoading} type="button">
            {isLoading ? "Refreshing..." : "Reload Matches"}
          </button>
        </div>
      </header>

      <section className="workspace-content-shell">
        {isLoading && (
          <section className="loading-stage" role="status" aria-live="polite">
            <div className="loader-orbit" aria-hidden="true">
              <span className="loader-ring" />
              <span className="loader-ring delay" />
            </div>
            <h2>Loading Match Data</h2>
            <p>Retrieving official Olympic football feeds and generating deterministic endpoint payloads.</p>

            <div className="loading-skeleton-grid" aria-hidden="true">
              <div className="loading-skeleton-card" />
              <div className="loading-skeleton-card" />
              <div className="loading-skeleton-card" />
            </div>
          </section>
        )}

        {!isLoading && error.length > 0 && (
          <StatePanel title={errorMessages.generationFailedTitle} message={error} isError />
        )}

        {!isLoading && !error && result && result.matches.length === 0 && (
          <StatePanel
            title="No Football Matches Found"
            message="No football matches were generated from the official source."
          />
        )}

        {!isLoading && !error && result && result.matches.length > 0 && (
          !selectedRecord ? (
            <section className="match-list-only">
              {matchListPanel}
            </section>
          ) : (
            <section className="master-detail-layout">
              {matchListPanel}

              <section className="match-detail-panel" aria-live="polite">
                <section className="detail-summary-layout">
                  <header className="detail-header">
                    <div className="detail-header-main">
                      <p className={`detail-status ${getStatusTone(selectedRecord.endpoint.status)}`}>
                        {selectedRecord.endpoint.status}
                      </p>
                      <h2 className="detail-matchup">
                        <span className="team-inline">
                          <TeamFlag
                            teamCode={selectedRecord.source.homeTeamCode}
                            teamName={selectedRecord.endpoint.teams.home}
                            size="lg"
                          />
                          <span>{selectedRecord.endpoint.teams.home}</span>
                        </span>
                        <span className="team-vs">vs</span>
                        <span className="team-inline">
                          <TeamFlag
                            teamCode={selectedRecord.source.awayTeamCode}
                            teamName={selectedRecord.endpoint.teams.away}
                            size="lg"
                          />
                          <span>{selectedRecord.endpoint.teams.away}</span>
                        </span>
                      </h2>
                      <p className="detail-header-meta">
                        {formatDateTime(selectedRecord.endpoint.kickoff)} | {selectedRecord.endpoint.venue.name},{" "}
                        {selectedRecord.endpoint.venue.city}
                      </p>

                      <dl className="detail-header-context">
                        <div>
                          <dt>Match Code</dt>
                          <dd>{selectedRecord.source.matchCode}</dd>
                        </div>
                        <div>
                          <dt>Event Code</dt>
                          <dd>{selectedRecord.source.eventCode}</dd>
                        </div>
                        <div>
                          <dt>Round</dt>
                          <dd>{selectedRecord.endpoint.competition.round}</dd>
                        </div>
                      </dl>
                    </div>

                    <div className="detail-header-side">
                      <div className="detail-score-card" aria-label="Match score">
                        <p className="detail-card-label">Scoreline</p>
                        <div className="detail-score">
                          <span>{selectedRecord.endpoint.score.home}</span>
                          <small>:</small>
                          <span>{selectedRecord.endpoint.score.away}</span>
                        </div>
                        <p className="detail-score-caption">{selectedRecord.endpoint.competition.round}</p>
                      </div>
                    </div>
                  </header>

                  <aside className="detail-summary-actions" aria-label="Inspection tools">
                    <article className="detail-actions-card">
                      <p className="detail-card-label">Inspection Actions</p>
                      <div className="detail-actions">
                        <button
                          className="control-button secondary"
                          onClick={() => handleOpenSingleMatchApi(selectedRecord.source.matchCode)}
                          type="button"
                        >
                          Open Single API
                        </button>
                        <button
                          className="control-button secondary"
                          onClick={() => handleExportSingleMatch(selectedRecord)}
                          type="button"
                        >
                          Export This Match
                        </button>
                        <button
                          className="control-button secondary"
                          onClick={handleToggleSourceContext}
                          disabled={isSourceContextLoading}
                          type="button"
                        >
                          {showSourceContext ? "Hide Full Source Context" : "Show Full Source Context"}
                        </button>
                      </div>
                    </article>
                  </aside>
                </section>

                <section className={`endpoint-inspection${showSourceContext ? " with-context" : ""}`}>
                  <article className="generated-endpoint-panel">
                    <div className="generated-endpoint-header">
                      <h3>Generated Endpoint</h3>

                      <div className="endpoint-view-toggle" role="group" aria-label="Generated endpoint view mode">
                        <button
                          className={`endpoint-view-button${endpointViewMode === "json" ? " active" : ""}`}
                          onClick={() => setEndpointViewMode("json")}
                          type="button"
                        >
                          JSON
                        </button>
                        <button
                          className={`endpoint-view-button${endpointViewMode === "simplified" ? " active" : ""}`}
                          onClick={() => setEndpointViewMode("simplified")}
                          type="button"
                        >
                          Simplified
                        </button>
                      </div>
                    </div>

                    {endpointViewMode === "json" ? (
                      <pre>{JSON.stringify(selectedRecord.endpoint, null, 2)}</pre>
                    ) : (
                      <section className="endpoint-simplified" aria-label="Simplified generated endpoint">
                        <div className="endpoint-simplified-grid">
                          <article className="endpoint-simplified-card">
                            <h4>Match</h4>
                            <p className="endpoint-value-strong">
                              {selectedRecord.endpoint.teams.home} vs {selectedRecord.endpoint.teams.away}
                            </p>
                            <p className="endpoint-muted">Kickoff: {formatDateTime(selectedRecord.endpoint.kickoff)}</p>
                            <p className="endpoint-muted">Status: {selectedRecord.endpoint.status}</p>
                          </article>

                          <article className="endpoint-simplified-card endpoint-simplified-score-card">
                            <h4>Score</h4>
                            <p className="endpoint-scoreline">
                              {selectedRecord.endpoint.score.home}
                              <span>:</span>
                              {selectedRecord.endpoint.score.away}
                            </p>
                            <p className="endpoint-muted">
                              Half-time {selectedRecord.endpoint.score.halfTime.home}:{" "}
                              {selectedRecord.endpoint.score.halfTime.away}
                            </p>
                          </article>

                          <article className="endpoint-simplified-card">
                            <h4>Competition</h4>
                            <p className="endpoint-value-strong">{selectedRecord.endpoint.competition.name}</p>
                            <p className="endpoint-muted">Season: {selectedRecord.endpoint.competition.season}</p>
                            <p className="endpoint-muted">Round: {selectedRecord.endpoint.competition.round}</p>
                          </article>

                          <article className="endpoint-simplified-card">
                            <h4>Venue</h4>
                            <p className="endpoint-value-strong">{selectedRecord.endpoint.venue.name}</p>
                            <p className="endpoint-muted">City: {selectedRecord.endpoint.venue.city}</p>
                          </article>
                        </div>

                        <article className="endpoint-simplified-card">
                          <h4>Scorers</h4>
                          {selectedRecord.endpoint.scorers.length === 0 ? (
                            <p className="endpoint-muted">No scorers were provided for this match.</p>
                          ) : (
                            <ul className="endpoint-scorers-list">
                              {selectedRecord.endpoint.scorers.map((scorer) => (
                                <li key={`${scorer.team}-${scorer.player}-${scorer.minute}-${scorer.type}`}>
                                  <span className="endpoint-scorer-minute">{`${scorer.minute}'`}</span>
                                  <span className="endpoint-scorer-main">
                                    <strong>{scorer.player}</strong> ({scorer.team})
                                  </span>
                                  <span className="endpoint-scorer-meta">
                                    {scorer.type}
                                    {scorer.assist ? ` | Assist: ${scorer.assist}` : ""}
                                  </span>
                                </li>
                              ))}
                            </ul>
                          )}
                        </article>

                        <article className="endpoint-simplified-card">
                          <h4>Lineups</h4>
                          <div className="endpoint-lineups-grid">
                            {(["home", "away"] as const).map((side) => {
                              const lineup = selectedRecord.endpoint.lineups[side];

                              return (
                                <section key={side} className="endpoint-lineup-card">
                                  <h5>{lineup.team}</h5>
                                  <p className="endpoint-lineup-meta">
                                    Formation: {lineup.formation} | Coach: {lineup.coach}
                                  </p>

                                  <div className="endpoint-lineup-columns">
                                    <section>
                                      <h6>Starting XI ({lineup.startingXI.length})</h6>
                                      <ol className="endpoint-player-list">
                                        {lineup.startingXI.map((player) => (
                                          <li key={`${side}-${player.number}-${player.name}-starting`}>
                                            <span>#{player.number}</span> {player.name} ({player.position})
                                          </li>
                                        ))}
                                      </ol>
                                    </section>

                                    <section>
                                      <h6>Bench ({lineup.bench.length})</h6>
                                      {lineup.bench.length === 0 ? (
                                        <p className="endpoint-muted">No bench players listed.</p>
                                      ) : (
                                        <ul className="endpoint-player-list">
                                          {lineup.bench.map((player) => (
                                            <li key={`${side}-${player.number}-${player.name}-bench`}>
                                              <span>#{player.number}</span> {player.name} ({player.position})
                                            </li>
                                          ))}
                                        </ul>
                                      )}
                                    </section>
                                  </div>
                                </section>
                              );
                            })}
                          </div>
                        </article>
                      </section>
                    )}
                  </article>

                  {showSourceContext && (
                    <section className="source-context-panel source-context-column" aria-live="polite">
                      <h3>Full Source Context</h3>
                      <p>
                        Combined per-match data pulled from connected official endpoints (StartList, EventUnits,
                        EventGames, Phases, Result, and Labels).
                      </p>

                      {isSourceContextLoading && (
                        <div className="source-context-loading" role="status" aria-live="polite">
                          <span className="source-context-spinner" aria-hidden="true" />
                          Loading all connected source inputs...
                        </div>
                      )}

                      {!isSourceContextLoading && sourceContextError.length > 0 && (
                        <p className="source-context-error">{sourceContextError}</p>
                      )}

                      {!isSourceContextLoading && !sourceContextError && selectedSourceContext && (
                        <pre>{JSON.stringify(selectedSourceContext, null, 2)}</pre>
                      )}
                    </section>
                  )}
                </section>
              </section>
            </section>
          )
        )}
      </section>
    </main>
  );
}
