"use client";

import { type ChangeEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";

import { MatchDetailPanel, type EndpointViewMode } from "@/components/home/MatchDetailPanel";
import {
  MatchListPanel,
  type MatchGenderFilter,
  type MatchListGrouping,
  type MatchListSection,
} from "@/components/home/MatchListPanel";
import { WorkspaceHeader } from "@/components/home/WorkspaceHeader";
import { StatePanel } from "@/components/StatePanel";
import { errorMessages } from "@/lib/errors/messages";
import { exportEndpointsToJson } from "@/lib/export/exportJson";
import type { GeneratedMatchRecord, GenerationResult, MatchSourceContext } from "@/lib/types/domain";
import type { MatchEndpoint } from "@/lib/types/endpoint";

interface ApiErrorResponse {
  error?: {
    title?: string;
    detail?: string;
  };
}

function getErrorMessage(payload: ApiErrorResponse | null): string {
  if (!payload?.error) {
    return errorMessages.generationFailedDetail;
  }

  const title = payload.error.title ?? errorMessages.generationFailedTitle;
  const detail = payload.error.detail ?? errorMessages.generationFailedDetail;

  return `${title}: ${detail}`;
}

function downloadText(fileName: string, content: string): void {
  const blob = new Blob([content], {
    type: "application/json",
  });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");

  anchor.href = url;
  anchor.download = fileName;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}

function downloadAllEndpoints(fileName: string, endpoints: MatchEndpoint[]): void {
  downloadText(fileName, exportEndpointsToJson(endpoints));
}

function downloadSingleEndpoint(fileName: string, endpoint: MatchEndpoint): void {
  downloadText(fileName, JSON.stringify(endpoint, null, 2));
}

function formatDateTime(value: string): string {
  const parsed = new Date(value);

  if (Number.isNaN(parsed.getTime())) {
    return value;
  }

  return new Intl.DateTimeFormat("en-GB", {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(parsed);
}

function getStatusTone(status: string): "status-live" | "status-finished" | "status-scheduled" {
  const normalized = status.trim().toLowerCase();

  if (normalized.includes("live") || normalized.includes("progress")) {
    return "status-live";
  }

  if (normalized.includes("finished") || normalized.includes("full") || normalized.includes("ended")) {
    return "status-finished";
  }

  return "status-scheduled";
}

function getMatchGender(record: GeneratedMatchRecord): MatchGenderFilter {
  const eventCodePrefix = record.source.eventCode.slice(0, 4).toUpperCase();

  if (eventCodePrefix === "FBLM") {
    return "men";
  }

  if (eventCodePrefix === "FBLW") {
    return "women";
  }

  return "all";
}

export default function HomePage() {
  const hasAutoGeneratedRef = useRef<boolean>(false);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [isSourceContextLoading, setIsSourceContextLoading] = useState<boolean>(false);
  const [showSourceContext, setShowSourceContext] = useState<boolean>(false);
  const [error, setError] = useState<string>("");
  const [sourceContextError, setSourceContextError] = useState<string>("");
  const [matchListGrouping, setMatchListGrouping] = useState<MatchListGrouping>("all");
  const [matchGenderFilter, setMatchGenderFilter] = useState<MatchGenderFilter>("all");
  const [endpointViewMode, setEndpointViewMode] = useState<EndpointViewMode>("json");
  const [result, setResult] = useState<GenerationResult | null>(null);
  const [selectedRecord, setSelectedRecord] = useState<GeneratedMatchRecord | null>(null);
  const [sourceContextByMatchCode, setSourceContextByMatchCode] = useState<
    Record<string, MatchSourceContext>
  >({});

  const endpoints = useMemo(() => {
    if (!result) {
      return [];
    }

    return result.matches.map((item: GenerationResult["matches"][number]) => item.endpoint);
  }, [result]);

  const filteredMatchRecords = useMemo<GeneratedMatchRecord[]>(() => {
    if (!result) {
      return [];
    }

    if (matchGenderFilter === "all") {
      return result.matches;
    }

    return result.matches.filter((record: GeneratedMatchRecord) => getMatchGender(record) === matchGenderFilter);
  }, [matchGenderFilter, result]);

  const matchListSections = useMemo<MatchListSection[]>(() => {
    if (!result) {
      return [];
    }

    if (matchListGrouping === "all") {
      return [
        {
          key: "all",
          title: "All matches",
          records: filteredMatchRecords,
        },
      ];
    }

    const groupedByRound = new Map<string, GeneratedMatchRecord[]>();

    for (const record of filteredMatchRecords) {
      const round = record.endpoint.competition.round.trim() || "Unknown Round";
      const existing = groupedByRound.get(round);

      if (existing) {
        existing.push(record);
        continue;
      }

      groupedByRound.set(round, [record]);
    }

    return Array.from(groupedByRound.entries()).map(([round, records]) => ({
      key: round,
      title: round,
      records,
    }));
  }, [filteredMatchRecords, matchListGrouping, result]);

  const handleGenerate = useCallback(async (): Promise<void> => {
    setIsLoading(true);
    setError("");

    try {
      const response = await fetch("/api/generate", {
        method: "POST",
      });

      if (!response.ok) {
        const payload = (await response.json().catch(() => null)) as ApiErrorResponse | null;
        setResult(null);
        setError(getErrorMessage(payload));
        return;
      }

      const payload = (await response.json()) as GenerationResult;

      setResult(payload);
      setSelectedRecord(null);
      setShowSourceContext(false);
      setSourceContextError("");
      setSourceContextByMatchCode({});
    } catch {
      setResult(null);
      setSelectedRecord(null);
      setShowSourceContext(false);
      setSourceContextError("");
      setSourceContextByMatchCode({});
      setError(errorMessages.generationFailedDetail);
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    setShowSourceContext(false);
    setSourceContextError("");
    setIsSourceContextLoading(false);
  }, [selectedRecord?.source.matchCode]);

  useEffect(() => {
    if (!selectedRecord) {
      return;
    }

    const selectedMatchCode = selectedRecord.source.matchCode;
    const isVisible = filteredMatchRecords.some((record) => record.source.matchCode === selectedMatchCode);

    if (isVisible) {
      return;
    }

    setSelectedRecord(null);
  }, [filteredMatchRecords, selectedRecord]);

  useEffect(() => {
    if (hasAutoGeneratedRef.current) {
      return;
    }

    hasAutoGeneratedRef.current = true;
    void handleGenerate();
  }, [handleGenerate]);

  const handleExport = (): void => {
    if (endpoints.length === 0) {
      return;
    }

    downloadAllEndpoints("olympic-football-endpoints.json", endpoints);
  };

  const handleOpenApi = (): void => {
    window.open("/api/generate", "_blank", "noopener,noreferrer");
  };

  const handleOpenSingleMatchApi = (matchCode: string): void => {
    const encodedMatchCode = encodeURIComponent(matchCode);
    window.open(`/api/generate?matchCode=${encodedMatchCode}`, "_blank", "noopener,noreferrer");
  };

  const handleExportSingleMatch = (record: GeneratedMatchRecord): void => {
    downloadSingleEndpoint(`olympic-football-endpoint-${record.source.matchCode}.json`, record.endpoint);
  };

  const selectedSourceContext = selectedRecord
    ? sourceContextByMatchCode[selectedRecord.source.matchCode]
    : undefined;

  const loadSourceContext = useCallback(async (matchCode: string): Promise<void> => {
    setIsSourceContextLoading(true);
    setSourceContextError("");

    try {
      const response = await fetch(
        `/api/generate?matchCode=${encodeURIComponent(matchCode)}&includeSourceContext=true`,
        {
          method: "GET",
          cache: "no-store",
        },
      );

      if (!response.ok) {
        const payload = (await response.json().catch(() => null)) as ApiErrorResponse | null;
        setSourceContextError(getErrorMessage(payload));
        return;
      }

      const payload = (await response.json()) as GenerationResult;
      const sourceContext = payload.matches[0]?.source.sourceContext;

      if (!sourceContext) {
        setSourceContextError("Full source context is not available for the selected match.");
        return;
      }

      setSourceContextByMatchCode((previous: Record<string, MatchSourceContext>) => ({
        ...previous,
        [matchCode]: sourceContext,
      }));
    } catch {
      setSourceContextError("Unable to load full source context for the selected match.");
    } finally {
      setIsSourceContextLoading(false);
    }
  }, []);

  const handleToggleSourceContext = (): void => {
    if (!selectedRecord) {
      return;
    }

    const nextValue = !showSourceContext;
    const matchCode = selectedRecord.source.matchCode;

    setShowSourceContext(nextValue);

    if (!nextValue) {
      return;
    }

    if (sourceContextByMatchCode[matchCode] || isSourceContextLoading) {
      return;
    }

    void loadSourceContext(matchCode);
  };

  const handleMatchListGroupingChange = (event: ChangeEvent<HTMLSelectElement>): void => {
    const nextGrouping = event.target.value === "round" ? "round" : "all";

    setMatchListGrouping(nextGrouping);
  };

  const handleMatchGenderFilterChange = (event: ChangeEvent<HTMLSelectElement>): void => {
    const nextGenderFilter =
      event.target.value === "men" || event.target.value === "women" ? event.target.value : "all";

    setMatchGenderFilter(nextGenderFilter);
  };

  const matchListPanel = result ? (
    <MatchListPanel
      result={result}
      visibleMatchesCount={filteredMatchRecords.length}
      matchListGrouping={matchListGrouping}
      matchGenderFilter={matchGenderFilter}
      matchListSections={matchListSections}
      selectedMatchCode={selectedRecord?.source.matchCode}
      onGroupingChange={handleMatchListGroupingChange}
      onGenderFilterChange={handleMatchGenderFilterChange}
      onSelectRecord={setSelectedRecord}
      formatDateTime={formatDateTime}
    />
  ) : null;

  return (
    <main className="match-workspace">
      <WorkspaceHeader
        isLoading={isLoading}
        hasEndpoints={endpoints.length > 0}
        onOpenApi={handleOpenApi}
        onExport={handleExport}
        onReload={handleGenerate}
      />

      <section className="workspace-content-shell">
        {isLoading && (
          <section className="loading-stage" role="status" aria-live="polite">
            <div className="loader-orbit" aria-hidden="true">
              <span className="loader-ring" />
              <span className="loader-ring delay" />
            </div>
            <h2>Loading Match Data</h2>
            <p>Retrieving official Olympic football feeds and generating deterministic endpoint payloads.</p>

            <div className="loading-skeleton-grid" aria-hidden="true">
              <div className="loading-skeleton-card" />
              <div className="loading-skeleton-card" />
              <div className="loading-skeleton-card" />
            </div>
          </section>
        )}

        {!isLoading && error.length > 0 && (
          <StatePanel title={errorMessages.generationFailedTitle} message={error} isError />
        )}

        {!isLoading && !error && result && result.matches.length === 0 && (
          <StatePanel
            title="No Football Matches Found"
            message="No football matches were generated from the official source."
          />
        )}

        {!isLoading && !error && result && result.matches.length > 0 && (
          !selectedRecord ? (
            <section className="match-list-only">
              {matchListPanel}
            </section>
          ) : (
            <section className="master-detail-layout">
              {matchListPanel}

              <MatchDetailPanel
                selectedRecord={selectedRecord}
                endpointViewMode={endpointViewMode}
                onEndpointViewModeChange={setEndpointViewMode}
                showSourceContext={showSourceContext}
                isSourceContextLoading={isSourceContextLoading}
                sourceContextError={sourceContextError}
                selectedSourceContext={selectedSourceContext}
                onOpenSingleMatchApi={handleOpenSingleMatchApi}
                onExportSingleMatch={handleExportSingleMatch}
                onToggleSourceContext={handleToggleSourceContext}
                formatDateTime={formatDateTime}
                getStatusTone={getStatusTone}
              />
            </section>
          )
        )}
      </section>
    </main>
  );
}
