"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";

import { MatchEndpointCard } from "@/components/MatchEndpointCard";
import { StatePanel } from "@/components/StatePanel";
import { errorMessages } from "@/lib/errors/messages";
import { exportEndpointsToJson } from "@/lib/export/exportJson";
import type { GeneratedMatchRecord, GenerationResult, MatchSourceContext } from "@/lib/types/domain";
import type { MatchEndpoint } from "@/lib/types/endpoint";

interface ApiErrorResponse {
  error?: {
    title?: string;
    detail?: string;
  };
}

function getErrorMessage(payload: ApiErrorResponse | null): string {
  if (!payload?.error) {
    return errorMessages.generationFailedDetail;
  }

  const title = payload.error.title ?? errorMessages.generationFailedTitle;
  const detail = payload.error.detail ?? errorMessages.generationFailedDetail;

  return `${title}: ${detail}`;
}

function downloadText(fileName: string, content: string): void {
  const blob = new Blob([content], {
    type: "application/json",
  });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");

  anchor.href = url;
  anchor.download = fileName;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}

function downloadAllEndpoints(fileName: string, endpoints: MatchEndpoint[]): void {
  downloadText(fileName, exportEndpointsToJson(endpoints));
}

function downloadSingleEndpoint(fileName: string, endpoint: MatchEndpoint): void {
  downloadText(fileName, JSON.stringify(endpoint, null, 2));
}

function formatDateTime(value: string): string {
  const parsed = new Date(value);

  if (Number.isNaN(parsed.getTime())) {
    return value;
  }

  return new Intl.DateTimeFormat("en-GB", {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(parsed);
}

function getStatusTone(status: string): "status-live" | "status-finished" | "status-scheduled" {
  const normalized = status.trim().toLowerCase();

  if (normalized.includes("live") || normalized.includes("progress")) {
    return "status-live";
  }

  if (normalized.includes("finished") || normalized.includes("full") || normalized.includes("ended")) {
    return "status-finished";
  }

  return "status-scheduled";
}

export default function HomePage() {
  const hasAutoGeneratedRef = useRef<boolean>(false);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [isSourceContextLoading, setIsSourceContextLoading] = useState<boolean>(false);
  const [showSourceContext, setShowSourceContext] = useState<boolean>(false);
  const [error, setError] = useState<string>("");
  const [sourceContextError, setSourceContextError] = useState<string>("");
  const [result, setResult] = useState<GenerationResult | null>(null);
  const [selectedRecord, setSelectedRecord] = useState<GeneratedMatchRecord | null>(null);
  const [sourceContextByMatchCode, setSourceContextByMatchCode] = useState<
    Record<string, MatchSourceContext>
  >({});

  const endpoints = useMemo(() => {
    if (!result) {
      return [];
    }

    return result.matches.map((item: GenerationResult["matches"][number]) => item.endpoint);
  }, [result]);

  const handleGenerate = useCallback(async (): Promise<void> => {
    setIsLoading(true);
    setError("");

    try {
      const response = await fetch("/api/generate", {
        method: "POST",
      });

      if (!response.ok) {
        const payload = (await response.json().catch(() => null)) as ApiErrorResponse | null;
        setResult(null);
        setError(getErrorMessage(payload));
        return;
      }

      const payload = (await response.json()) as GenerationResult;

      setResult(payload);
      setSelectedRecord(null);
      setShowSourceContext(false);
      setSourceContextError("");
      setSourceContextByMatchCode({});
    } catch {
      setResult(null);
      setSelectedRecord(null);
      setShowSourceContext(false);
      setSourceContextError("");
      setSourceContextByMatchCode({});
      setError(errorMessages.generationFailedDetail);
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    setShowSourceContext(false);
    setSourceContextError("");
    setIsSourceContextLoading(false);
  }, [selectedRecord?.source.matchCode]);

  useEffect(() => {
    if (hasAutoGeneratedRef.current) {
      return;
    }

    hasAutoGeneratedRef.current = true;
    void handleGenerate();
  }, [handleGenerate]);

  const handleExport = (): void => {
    if (endpoints.length === 0) {
      return;
    }

    downloadAllEndpoints("olympic-football-endpoints.json", endpoints);
  };

  const handleOpenApi = (): void => {
    window.open("/api/generate", "_blank", "noopener,noreferrer");
  };

  const handleOpenSingleMatchApi = (matchCode: string): void => {
    const encodedMatchCode = encodeURIComponent(matchCode);
    window.open(`/api/generate?matchCode=${encodedMatchCode}`, "_blank", "noopener,noreferrer");
  };

  const handleExportSingleMatch = (record: GeneratedMatchRecord): void => {
    downloadSingleEndpoint(`olympic-football-endpoint-${record.source.matchCode}.json`, record.endpoint);
  };

  const selectedSourceContext = selectedRecord
    ? sourceContextByMatchCode[selectedRecord.source.matchCode]
    : undefined;

  const loadSourceContext = useCallback(async (matchCode: string): Promise<void> => {
    setIsSourceContextLoading(true);
    setSourceContextError("");

    try {
      const response = await fetch(
        `/api/generate?matchCode=${encodeURIComponent(matchCode)}&includeSourceContext=true`,
        {
          method: "GET",
          cache: "no-store",
        },
      );

      if (!response.ok) {
        const payload = (await response.json().catch(() => null)) as ApiErrorResponse | null;
        setSourceContextError(getErrorMessage(payload));
        return;
      }

      const payload = (await response.json()) as GenerationResult;
      const sourceContext = payload.matches[0]?.source.sourceContext;

      if (!sourceContext) {
        setSourceContextError("Full source context is not available for the selected match.");
        return;
      }

      setSourceContextByMatchCode((previous: Record<string, MatchSourceContext>) => ({
        ...previous,
        [matchCode]: sourceContext,
      }));
    } catch {
      setSourceContextError("Unable to load full source context for the selected match.");
    } finally {
      setIsSourceContextLoading(false);
    }
  }, []);

  const handleToggleSourceContext = (): void => {
    if (!selectedRecord) {
      return;
    }

    const nextValue = !showSourceContext;
    const matchCode = selectedRecord.source.matchCode;

    setShowSourceContext(nextValue);

    if (!nextValue) {
      return;
    }

    if (sourceContextByMatchCode[matchCode] || isSourceContextLoading) {
      return;
    }

    void loadSourceContext(matchCode);
  };

  return (
    <main className="match-workspace">
      <header className="workspace-header">
        <div>
          <p className="workspace-eyebrow">Paris 2024 Football</p>
          <h1>footy-scores</h1>
          <p className="workspace-subtitle">
            Compact fixture list for inspection. Select any match to review generated payload details and source data.
          </p>
        </div>

        <div className="workspace-actions">
          <button className="control-button secondary" onClick={handleOpenApi} type="button">
            Open API JSON
          </button>
          <button
            className="control-button secondary"
            onClick={handleExport}
            disabled={endpoints.length === 0}
            type="button"
          >
            Export All
          </button>
          <button className="control-button" onClick={handleGenerate} disabled={isLoading} type="button">
            {isLoading ? "Refreshing..." : "Reload Matches"}
          </button>
        </div>
      </header>

      <section className="workspace-content-shell">
        {isLoading && (
          <section className="loading-stage" role="status" aria-live="polite">
            <div className="loader-orbit" aria-hidden="true">
              <span className="loader-ring" />
              <span className="loader-ring delay" />
            </div>
            <h2>Loading Match Data</h2>
            <p>Retrieving official Olympic football feeds and generating deterministic endpoint payloads.</p>

            <div className="loading-skeleton-grid" aria-hidden="true">
              <div className="loading-skeleton-card" />
              <div className="loading-skeleton-card" />
              <div className="loading-skeleton-card" />
            </div>
          </section>
        )}

        {!isLoading && error.length > 0 && (
          <StatePanel title={errorMessages.generationFailedTitle} message={error} isError />
        )}

        {!isLoading && !error && result && result.matches.length === 0 && (
          <StatePanel
            title="No Football Matches Found"
            message="No football matches were generated from the official source."
          />
        )}

        {!isLoading && !error && result && result.matches.length > 0 && (
          !selectedRecord ? (
            <section className="match-list-only">
              <aside className="match-list-panel" aria-label="Generated football match list">
                <header>
                  <h2>Matches</h2>
                  <p>{result.matches.length} fixtures available</p>
                  <p className="list-meta">Generated at {formatDateTime(result.diagnostics.generatedAt)}</p>
                </header>

                <div className="match-list-scroll list-only-grid">
                  {result.matches.map((record: GenerationResult["matches"][number]) => (
                    <MatchEndpointCard
                      key={record.source.matchCode}
                      record={record}
                      isSelected={false}
                      onOpen={setSelectedRecord}
                    />
                  ))}
                </div>
              </aside>
            </section>
          ) : (
            <section className="master-detail-layout">
              <aside className="match-list-panel" aria-label="Generated football match list">
                <header>
                  <h2>Matches</h2>
                  <p>{result.matches.length} fixtures available</p>
                  <p className="list-meta">Generated at {formatDateTime(result.diagnostics.generatedAt)}</p>
                </header>

                <div className="match-list-scroll">
                  {result.matches.map((record: GenerationResult["matches"][number]) => (
                    <MatchEndpointCard
                      key={record.source.matchCode}
                      record={record}
                      isSelected={selectedRecord?.source.matchCode === record.source.matchCode}
                      onOpen={setSelectedRecord}
                    />
                  ))}
                </div>
              </aside>

              <section className="match-detail-panel" aria-live="polite">
                <header className="detail-header">
                  <div className="detail-header-main">
                    <p className={`detail-status ${getStatusTone(selectedRecord.endpoint.status)}`}>
                      {selectedRecord.endpoint.status}
                    </p>
                    <h2>
                      {selectedRecord.endpoint.teams.home} vs {selectedRecord.endpoint.teams.away}
                    </h2>
                    <p className="detail-header-meta">
                      {formatDateTime(selectedRecord.endpoint.kickoff)} | {selectedRecord.endpoint.venue.name},{" "}
                      {selectedRecord.endpoint.venue.city}
                    </p>
                  </div>

                  <div className="detail-score-card" aria-label="Match score">
                    <p className="detail-card-label">Scoreline</p>
                    <div className="detail-score">
                      <span>{selectedRecord.endpoint.score.home}</span>
                      <small>:</small>
                      <span>{selectedRecord.endpoint.score.away}</span>
                    </div>
                    <p className="detail-score-caption">{selectedRecord.endpoint.competition.round}</p>
                  </div>
                </header>

                <section className="detail-overview-grid" aria-label="Selected match overview">
                  <article className="detail-overview-card">
                    <p className="detail-card-label">Match Metadata</p>
                    <dl className="detail-meta-grid">
                      <div>
                        <dt>Match Code</dt>
                        <dd>{selectedRecord.source.matchCode}</dd>
                      </div>
                      <div>
                        <dt>Event Code</dt>
                        <dd>{selectedRecord.source.eventCode}</dd>
                      </div>
                      <div>
                        <dt>Round</dt>
                        <dd>{selectedRecord.endpoint.competition.round}</dd>
                      </div>
                      <div>
                        <dt>Source Mode</dt>
                        <dd>{selectedRecord.source.sourceMode}</dd>
                      </div>
                    </dl>
                  </article>

                  <article className="detail-overview-card">
                    <p className="detail-card-label">Inspection Actions</p>
                    <div className="detail-actions">
                      <button
                        className="control-button secondary"
                        onClick={() => handleOpenSingleMatchApi(selectedRecord.source.matchCode)}
                        type="button"
                      >
                        Open Single API
                      </button>
                      <button
                        className="control-button secondary"
                        onClick={() => handleExportSingleMatch(selectedRecord)}
                        type="button"
                      >
                        Export This Match
                      </button>
                      <button
                        className="control-button secondary"
                        onClick={handleToggleSourceContext}
                        disabled={isSourceContextLoading}
                        type="button"
                      >
                        {showSourceContext ? "Hide Full Source Context" : "Show Full Source Context"}
                      </button>
                    </div>
                  </article>
                </section>

                <div className="detail-json-grid">
                  <article>
                    <h3>Source Match Data</h3>
                    <pre>{JSON.stringify(selectedRecord.source, null, 2)}</pre>
                  </article>

                  <article>
                    <h3>Generated Endpoint</h3>
                    <pre>{JSON.stringify(selectedRecord.endpoint, null, 2)}</pre>
                  </article>
                </div>

                {showSourceContext && (
                  <section className="source-context-panel" aria-live="polite">
                    <h3>Full Source Context</h3>
                    <p>
                      Combined per-match data pulled from connected official endpoints (StartList, EventUnits,
                      EventGames, Phases, Result, and Labels).
                    </p>

                    {isSourceContextLoading && (
                      <div className="source-context-loading" role="status" aria-live="polite">
                        <span className="source-context-spinner" aria-hidden="true" />
                        Loading all connected source inputs...
                      </div>
                    )}

                    {!isSourceContextLoading && sourceContextError.length > 0 && (
                      <p className="source-context-error">{sourceContextError}</p>
                    )}

                    {!isSourceContextLoading && !sourceContextError && selectedSourceContext && (
                      <pre>{JSON.stringify(selectedSourceContext, null, 2)}</pre>
                    )}
                  </section>
                )}
              </section>
            </section>
          )
        )}
      </section>
    </main>
  );
}
